In [1]:
Yield_of_Apples = w1 * temperature + w2 * rainfall + w3 * humidity

In [2]:
w1 , w2 , w3 = 0.3 , 0.2 , 0.5

In [3]:
lahore_temp = 73
lahore_rainfall = 67
lahore_humidity = 43


In [4]:
lahore_yeild_apples = lahore_temp * w1 + lahore_rainfall * w2 + lahore_humidity*w3

In [5]:
print('The expected yield of apples in lahore regin is {} tons per hectare.'.format(lahore_yeild_apples))

The expected yield of apples in lahore regin is 56.8 tons per hectare.


In [6]:
lahore = [73, 67, 43]
karachi = [91, 88, 64]
faisalabad = [87, 134, 68]
peshawar = [102, 78, 99]
weights = [w1, w2, w3 ]

In [7]:
def crop_yield(region, weights):
    result = 0 
    for x, w in zip(region,weights):
        result += x*w
    return result

In [8]:
crop_yield(lahore, weights)


56.8

In [9]:
a = crop_yield(lahore, weights)
b= crop_yield(karachi, weights)
c= crop_yield(faisalabad, weights)
d= crop_yield(peshawar, weights)


In [10]:
print('The expected yield of apples in lahore regin is {} tons per hectare.'.format(a))
print('The expected yield of apples in karachi regin is {} tons per hectare.'.format(b))
print('The expected yield of apples in faisalabad regin is {} tons per hectare.'.format(c))
print('The expected yield of apples in peshawar regin is {} tons per hectare.'.format(d))


The expected yield of apples in lahore regin is 56.8 tons per hectare.
The expected yield of apples in karachi regin is 76.9 tons per hectare.
The expected yield of apples in faisalabad regin is 86.9 tons per hectare.
The expected yield of apples in peshawar regin is 95.7 tons per hectare.


# Numpy Arrays 

In [11]:
import numpy as np 

In [12]:
lahore = np.array([73, 67, 43])
weights = np.array([w1, w2, w3])
print(type(lahore))
print(type(weights))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [13]:
apple_of_yield = np.dot(lahore, weights)
print(apple_of_yield)


56.8


In [14]:
apple_of_yield = np.dot(lahore , weights)
print(apple_of_yield)

56.8


# Multi-Dimensional Numpy Arrays 

In [15]:
climate_data = np.array([[73, 67, 43], 
                         [91, 88, 64],
                         [87, 134, 68],
                         [102, 78, 99]])

In [16]:
climate_data.shape
# its a 2-D array 

(4, 3)

In [17]:
climate_data [2,0:3]

array([ 87, 134,  68])

In [18]:
weights.dtype

dtype('float64')

In [19]:
type(weights)

numpy.ndarray

In [20]:
# Its a one-D array 
weights.shape

(3,)

In [21]:
# 3-D array 
data = np.array([[[73, 67, 43], 
                  [91, 88, 64],
                 [91, 88, 64]],
                 [[87, 134, 68],
                  [87, 134, 68],
                [102, 78, 99]]])


In [22]:
data

array([[[ 73,  67,  43],
        [ 91,  88,  64],
        [ 91,  88,  64]],

       [[ 87, 134,  68],
        [ 87, 134,  68],
        [102,  78,  99]]])

In [23]:
type(data)

numpy.ndarray

In [24]:

data.shape

(2, 3, 3)

In [25]:
data.dtype

dtype('int32')

In [26]:
climate_data @ weights

array([56.8, 76.9, 86.9, 95.7])

In [27]:
np.matmul(climate_data , weights)

array([56.8, 76.9, 86.9, 95.7])

In [28]:
climate_data_1 = np.genfromtxt('New Text Document11.csv', delimiter=',', skip_header=1)

In [33]:
climate_data_1.shape

(10000, 3)

In [34]:
yeilds = climate_data_1 @ weights 

In [35]:
yeilds

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [36]:
yeilds.shape

(10000,)

In [39]:

climate_results = np.insert(climate_data_1, 3, yeilds, axis=1)
print (climate_results)

[[25.  76.  99.  72.2]
 [39.  65.  70.  59.7]
 [59.  45.  77.  65.2]
 ...
 [99.  62.  58.  71.1]
 [70.  71.  91.  80.7]
 [92.  39.  76.  73.4]]


In [40]:
yeilds.shape

(10000,)

In [44]:
yeilds

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [52]:
# Alternate Way to add a column in array 
climate_results_1 = np.concatenate((climate_data_1, yeilds.reshape(10000, 1)), axis=1)

In [53]:
climate_results_1

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [63]:
# Save the data in CSV File Back. 

np.savetxt("climate_results_data1.csv", climate_results_1, fmt='%.2f', delimiter = "," , header = 'temperature,rainfall,humadity,yeild_apple',comments='')

## Arithmetic operations, broadcasting and comparison 

In [64]:
array_1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])


In [65]:
array_2 = np.array([[11, 12, 13, 14],
                   [15, 16, 17, 18],
                   [19, 20, 21, 22]])

In [66]:
array_1+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [67]:
array_1/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ]])

In [68]:
array_1//2

array([[0, 1, 1, 2],
       [2, 3, 3, 4],
       [4, 5, 5, 6]], dtype=int32)

In [69]:
array_1 + array_2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [71]:
array_2.shape

(3, 4)

In [72]:
array_3 = np.array([2,3,4,5])

In [73]:
array_3.shape

(4,)

In [74]:
array_2 +array_3

array([[13, 15, 17, 19],
       [17, 19, 21, 23],
       [21, 23, 25, 27]])

In [75]:
array_1 == array_2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [78]:
array_2 != array_1

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Array comparison is frequently used to count the number of equal elements in two arrays using the sum method. Remember that True evaluates to 1 and False evaluates to 0 when booleans are used in arithmetic operations.

In [83]:
(array_1 == array_2).sum()

0

In [84]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])


In [86]:
arr3.shape

(3, 2, 4)

In [89]:
arr3 [1, 0,0]

15.0

In [90]:
arr3 [2,0,3]

23.0

In [95]:
array_4 = np.array([
           [[0, 1, 2, 3, 4,5],
           [10, 11, 12, 13, 14, 15]],
    
           [[20, 21, 22, 23, 24, 25],
           [30, 31, 32, 33, 34, 35]],
        
           [[40, 41, 42, 43, 44, 45],
           [50, 51, 52, 53, 54, 55]]])

In [96]:
array_4

array([[[ 0,  1,  2,  3,  4,  5],
        [10, 11, 12, 13, 14, 15]],

       [[20, 21, 22, 23, 24, 25],
        [30, 31, 32, 33, 34, 35]],

       [[40, 41, 42, 43, 44, 45],
        [50, 51, 52, 53, 54, 55]]])

In [98]:
array_4.shape

(3, 2, 6)

In [100]:
array_4 [0, 0, 3:5]

array([3, 4])

In [101]:
array_4 [0:5, 0:5, 2]

array([[ 2, 12],
       [22, 32],
       [42, 52]])

In [111]:
array_4[2,0:2 ,4 :6]

array([[44, 45],
       [54, 55]])